### ISSUE TITLE
Unable to use @InjectQueue in other modules

### ISSUE THREAD

**Issue by GeekyGeeky** [jongolden/agenda-nest#21]
`Nest can't resolve dependencies of the MiscSerice (CATEGORY_MODEL, ?). Please make sure that the argument wallets-queue at index [1] is available in the MiscModule context.`

I get the error above when I tried to use @InjectQueue in my other modules. I have imported the JobModule in the Module but it still gives me the error

```
Potential solutions:
- If wallets-queue is a provider, is it part of the current MiscModule?
- If wallets-queue is exported from a separate @Module, is that module imported within MiscModule?
  @Module({
    imports: [ /* the Module containing wallets-queue */ ]
  })
```
  
  I have tried the possible solutions above too

**Comment by jongolden** [comment]
@GeekyGeeky, Can you please show how you are linking up `.forRoot` and `.registerQueue`?

**Comment by GeekyGeeky** [comment]
```
   AgendaModule.forRootAsync({
      useFactory: (mongooseConnection: any) => ({
        mongo: mongooseConnection,
      }),
      inject: [DBConnection],
      // extraProviders: [databaseProvider],
    }),
```
I have this in my app.module.ts and it works fine

```
@Module({
  imports: [AgendaModule.registerQueue('wallets')],
  providers: [WalletsQueue],
  exports: [WalletsQueue],
})
export class WalletJobModule {}
```

My job module looks like this and it is imported in my app.module.ts also

**Comment by GeekyGeeky** [comment]
Thanks for your help 😁, this worked for me. I will close the issue now. Anyone who faces a similar issue can use this as a reference 👍.
