### ISSUE TITLE
Don't force a dash in queue collection name

### ISSUE THREAD

**Issue by tomtastico** [jongolden/agenda-nest#25]
Right now the collection name for a queue is hardcoded to be `${name}-queue`, but using dashes / hyphens in mongdb collections can be problematic (in our case, it's giving us problems with a custom import / export job)

https://devops.datenkollektiv.de/why-you-shouldnt-use-a-dash-in-a-mongodb-collection-name.html
https://coderwall.com/p/lhxbtq/do-not-use-hyphens-in-mongodb-collection-names

Would it be possible to have one of these options?

- Have `${name}queue` as name for the collection (no dash).
- Not add anything, just name the collection `name` and the user can choose to add a suffix if desired as part of the name.
- Allow to define a custom suffix in the `@Queue` decorator.
- Allow to define a full collection name without suffix in the `@Queue` decorator.

I was checking the parameters for `@Queue` and I see that it might be possible to change the collection name by passing an `AgendaConfig` object to the `@Queue` decorator, in the `db.collection` property, but unfortunately that also requires to define `db.address` which is the mongodb connection string and I don't want to do that, I want it to use the already configured mongo connection just like when you only provide a queue name.

```
export interface AgendaConfig {
  name?: string;
  processEvery?: string;
  maxConcurrency?: number;
  defaultConcurrency?: number;
  lockLimit?: number;
  defaultLockLimit?: number;
  defaultLockLifetime?: number;
  sort?: any;
  mongo?: MongoDb;
  db?: {
    address: string; // I don't want to have to provide the mongodb connection string just for this, but it's not optional
    collection?: string; // I suppose with this I can set my own collection name, without -queue
    options?: MongoClientOptions;
  };
  disableAutoIndex?: boolean;
}
```

**Comment by jongolden** [comment]
This is fair.  Unfortunately, the first option would cause a breaking change.

Allowing for an optional collection name would probably be the best way forward and can easily be achieved by adding the option to the `AgendaQueueConfig`.  This will allow the collection to be defined either in the decorator or in `registerQueue`.

While looking at this, I noticed that the `Queue` decorator needs to be using this same type as well.  This won't be a breaking change since we extend `AgendaConfig`, omitting the `mongo` and `db` properties which we don't use in the orchestrator.

**Comment by jongolden** [comment]
@tomtastico, do you have capacity to put in a PR for this?  If not, I can take it up this weekend.

**Comment by tomtastico** [comment]
@jongolden I will try for a PR later today or tomorrow, otherwise I won't be able until sometime next week.

So you preferred option is to add a `collection` option to `AgendaQueueConfig` , just like you added `autoStart`, right? And update the `@Queue` decorator to accept `AgendaQueueConfig` instead of `AgendaConfig`.

**Comment by jongolden** [comment]
@tomtastico Yeah, exactly
